name: CIPR-128

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]
 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: peter-evans/create-pull-request@v4
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "👑 *An automated PR*"
        pr_reviewer: "pillakathupunageswarao128@gmail.com"
        pr_draft: false
        github_token: "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"
